---
after_script:
- rake travis:after -t
before_script:
- gem install hoe-travis --no-document
- rake travis:before -t
sudo: false
cache:
  - bundler
  - directories:
    - /home/travis/.rvm/
language: ruby
notifications:
  email:
rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3
  - jruby-9.2.7.0
  - ruby-head
script: rake travis
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.2.7.0
